import Foundation
import IntatisCore
import IntatisProtocol

/// Raw JSON arguments for a tool call, with a typed decode helper.
public struct ToolArgs: Sendable {
    public let raw: String
    public init(raw: String) { self.raw = raw }

    public func decode<T: Decodable>(_ type: T.Type) throws -> T {
        guard let data = raw.data(using: .utf8) else {
            throw IntatisError.decoding("tool args are not valid UTF-8")
        }
        do {
            return try JSONDecoder().decode(T.self, from: data)
        } catch {
            throw IntatisError.decoding("tool args: \(error.localizedDescription)")
        }
    }
}

/// The result of executing a tool. `diff`/`changedFiles` are set by mutating tools.
public struct ToolObservation: Equatable, Sendable {
    public var text: String
    public var truncated: Bool
    public var diff: String?
    public var changedFiles: [String]?
    public init(text: String, truncated: Bool = false, diff: String? = nil, changedFiles: [String]? = nil) {
        self.text = text
        self.truncated = truncated
        self.diff = diff
        self.changedFiles = changedFiles
    }
}

/// Static metadata the permission gate reads. Tools are dumb executors; they do
/// not decide whether they may run (ARCHITECTURE.md §1.2 principle E).
public struct ToolDescriptor: Sendable {
    public let name: String
    public let description: String
    public let sideEffect: SideEffect
    public let parameters: JSONValue   // JSON-Schema object
    public init(name: String, description: String, sideEffect: SideEffect, parameters: JSONValue) {
        self.name = name
        self.description = description
        self.sideEffect = sideEffect
        self.parameters = parameters
    }
}

// MARK: - Injected services (keep tools testable + backend-swappable)

public struct ShellResult: Equatable, Sendable {
    public var stdout: String
    public var stderr: String
    public var exitCode: Int
    public init(stdout: String, stderr: String, exitCode: Int) {
        self.stdout = stdout
        self.stderr = stderr
        self.exitCode = exitCode
    }
}

public struct GitPatchResult: Equatable, Sendable {
    public var text: String
    public var changedFiles: [String]
    public var diff: String
    public init(text: String, changedFiles: [String], diff: String) {
        self.text = text
        self.changedFiles = changedFiles
        self.diff = diff
    }
}

public protocol ShellRunner: Sendable {
    func run(_ command: String, cwd: URL) async throws -> ShellResult
}

/// Git backend. v0.2 dev uses `ProcessGitService` (spawns git); the App Store
/// sandbox build swaps in a libgit2-backed implementation (ARCHITECTURE.md §9.1).
public protocol GitService: Sendable {
    func status(workspace: URL) async throws -> String   // porcelain v1
    func diff(workspace: URL) async throws -> String      // unified diff
    func stagedDiff(workspace: URL) async throws -> String // unified diff for index
    func repositoryInfo(workspace: URL) async throws -> String
    func recentCommits(limit: Int, workspace: URL) async throws -> String
    func diffAgainst(base: String, workspace: URL) async throws -> String
    func branchInfo(workspace: URL) async throws -> String
    func createBranch(name: String, startPoint: String?, workspace: URL) async throws -> String
    func stage(paths: [String], workspace: URL) async throws -> String
    func unstage(paths: [String], workspace: URL) async throws -> String
    func commit(message: String, workspace: URL) async throws -> String
    func applyPatch(diff: String, reverse: Bool, checkOnly: Bool, cached: Bool, workspace: URL) async throws -> GitPatchResult
    func worktrees(workspace: URL) async throws -> String
    func createWorktree(name: String, startPoint: String?, branch: String?, workspace: URL) async throws -> String
    func removeWorktree(name: String, force: Bool, workspace: URL) async throws -> String
    func remotes(workspace: URL) async throws -> String
    func fetch(remote: String, branch: String?, prune: Bool, workspace: URL) async throws -> String
    func pullFastForward(remote: String, branch: String, workspace: URL) async throws -> String
    func push(remote: String, branch: String, setUpstream: Bool, workspace: URL) async throws -> String
    func switchBranch(name: String, workspace: URL) async throws -> String
}

/// Provider-backed or local-model image generation service injected by the app
/// or CLI. The tool layer owns path validation; the service owns model/provider
/// resolution and writing generated bytes to the requested workspace path.
public protocol ImageGenerationToolService: Sendable {
    func generateImage(prompt: String,
                       size: String,
                       count: Int,
                       outputPath: String,
                       workspaceRoot: URL) async throws -> ToolObservation
}

/// Seam for agent-to-agent messaging (v0.3). Cowork provides an implementation
/// bound to the asking agent; the `ask_agent` tool routes through it so all
/// cross-agent traffic goes through the mediated Message Bus (ARCHITECTURE.md §7).
public protocol AgentMessenger: Sendable {
    func ask(to agent: String, question: String) async -> String
    func sendMessage(to agent: String, content: String) async -> String
    func requestInformation(to agent: String, question: String) async -> String
    func replyMessage(to agent: String, content: String, inReplyTo: String?) async -> String
    func requestDelegation(objective: String, reason: String) async -> String
    func delegateTask(to agent: String?,
                      objective: String,
                      roleHint: String?,
                      expectedDeliverable: String?) async -> String
}

/// Seam for agent lifecycle management (v0.3 coordinator). Cowork provides an
/// implementation bound to the orchestrator so a coordinator agent can create,
/// list, and remove sub-agents through tools. Like `AgentMessenger`, the real
/// work happens in the orchestrator/registry — tools are just thin executors.
public protocol AgentManager: Sendable {
    func spawnAgent(name: String,
                    path: String,
                    model: String?,
                    requestedAccess: WorkspaceAccess,
                    canCoordinate: Bool) async -> String
    func listAgents() async -> String
    func removeAgent(name: String) async -> String
}

public struct ToolContext: Sendable {
    public let workspaceRoot: URL
    /// Effective task/workspace lease. Direct tool hosts that omit it receive
    /// the standard read-write lease (including default secret deny patterns),
    /// so process-backed tools never silently run with a wider policy.
    public let workspaceLease: WorkspaceLease
    /// Raw, model-authored shell commands. The default runner is workspace and
    /// network confined.
    public let shell: ShellRunner
    /// Shell backend for structured Swift tools (browser/document wrappers)
    /// whose arguments and paths have already been validated by the tool. This
    /// runner is workspace-confined and network-denied.
    public let structuredShell: ShellRunner
    /// Dedicated workspace-confined structured runner for tools whose
    /// descriptor and permission request explicitly declare network access.
    /// Keeping this separate prevents a document/LaTeX wrapper from inheriting
    /// browser network authority merely because both are process-backed.
    public let networkStructuredShell: ShellRunner
    public let git: GitService
    public let messenger: AgentMessenger?
    public let agentManager: AgentManager?
    public let imageGenerator: ImageGenerationToolService?
    public init(workspaceRoot: URL,
                workspaceLease: WorkspaceLease? = nil,
                shell: ShellRunner = ProcessShellRunner(),
                structuredShell: ShellRunner? = nil,
                networkStructuredShell: ShellRunner? = nil,
                git: GitService = ProcessGitService(),
                messenger: AgentMessenger? = nil,
                agentManager: AgentManager? = nil,
                imageGenerator: ImageGenerationToolService? = nil) {
        let effectiveLease = workspaceLease ?? WorkspaceLease(
            rootPath: workspaceRoot.resolvingSymlinksInPath().standardizedFileURL.path,
            access: .readWrite)
        self.workspaceRoot = workspaceRoot
        self.workspaceLease = effectiveLease
        if let processShell = shell as? ProcessShellRunner {
            self.shell = processShell.scoped(to: effectiveLease)
        } else {
            self.shell = shell
        }
        let resolvedStructuredShell: ShellRunner
        if let structuredShell {
            if let processShell = structuredShell as? StructuredProcessShellRunner {
                resolvedStructuredShell = processShell.scoped(to: effectiveLease)
            } else if let processShell = structuredShell as? ProcessShellRunner {
                resolvedStructuredShell = processShell.scoped(to: effectiveLease)
            } else {
                resolvedStructuredShell = structuredShell
            }
        } else if shell is ProcessShellRunner {
            resolvedStructuredShell = StructuredProcessShellRunner(workspaceLease: effectiveLease)
        } else {
            // Preserve injected fake runners in unit tests and custom hosts.
            resolvedStructuredShell = shell
        }
        self.structuredShell = resolvedStructuredShell
        if let networkStructuredShell {
            if let processShell = networkStructuredShell as? StructuredProcessShellRunner {
                self.networkStructuredShell = processShell.scoped(to: effectiveLease)
            } else if let processShell = networkStructuredShell as? ProcessShellRunner {
                self.networkStructuredShell = processShell.scoped(to: effectiveLease)
            } else {
                self.networkStructuredShell = networkStructuredShell
            }
        } else if shell is ProcessShellRunner, structuredShell == nil {
            self.networkStructuredShell = StructuredProcessShellRunner(
                allowsNetwork: true,
                workspaceLease: effectiveLease)
        } else {
            // Preserve the pre-existing single fake-runner injection behavior.
            self.networkStructuredShell = resolvedStructuredShell
        }
        if let processGit = git as? ProcessGitService {
            self.git = processGit.scoped(to: effectiveLease)
        } else {
            self.git = git
        }
        self.messenger = messenger
        self.agentManager = agentManager
        self.imageGenerator = imageGenerator
    }
}

// MARK: - Tool

public protocol Tool: Sendable {
    static var descriptor: ToolDescriptor { get }
    func touchedPaths(_ args: ToolArgs) -> [String]
    func risksNetwork(_ args: ToolArgs) -> Bool
    /// Build the structured authorization input for this exact invocation.
    /// `workspaceRoot` is context only; it is not an approval or a replacement
    /// for CapabilityLease / WorkspaceLease enforcement in AgentKernel.
    func permissionIntent(_ args: ToolArgs, workspaceRoot: URL) -> PermissionIntent
    func execute(_ args: ToolArgs, in context: ToolContext) async throws -> ToolObservation
}

public extension Tool {
    func touchedPaths(_ args: ToolArgs) -> [String] { [] }
    func risksNetwork(_ args: ToolArgs) -> Bool { false }
    func permissionIntent(_ args: ToolArgs, workspaceRoot: URL) -> PermissionIntent {
        let descriptor = Self.descriptor
        var intent = PermissionIntent.derived(
            toolName: descriptor.name,
            sideEffect: descriptor.sideEffect,
            touchedPaths: touchedPaths(args),
            risksNetwork: risksNetwork(args))
        guard let object = Self.permissionArgumentObject(args) else { return intent }

        if descriptor.name == "run_shell",
           case .string(let command)? = object["command"] {
            intent.resources.append(PermissionResource(kind: .command, value: command))
        }
        if descriptor.name.hasPrefix("git_") {
            intent.resources.append(PermissionResource(kind: .git, value: workspaceRoot.path))
            for key in ["remote", "branch", "base", "name", "startPoint"] {
                if case .string(let value)? = object[key] {
                    intent.metadata[key] = .string(value)
                }
            }
        }
        if descriptor.name.hasPrefix("browser_") || descriptor.name == "web_fetch" {
            for key in ["url", "startURL"] {
                if case .string(let value)? = object[key] {
                    intent.resources.append(PermissionResource(kind: .url, value: value))
                }
            }
            if case .string(let query)? = object["query"] {
                intent.metadata["query"] = .string(query)
            }
        }
        return intent
    }

    private static func permissionArgumentObject(_ args: ToolArgs) -> [String: JSONValue]? {
        guard let data = args.raw.data(using: .utf8),
              let decoded = try? JSONDecoder().decode(JSONValue.self, from: data),
              case .object(let object) = decoded else { return nil }
        return object
    }
}

public struct ToolRegistry: Sendable {
    private let tools: [String: any Tool]

    public init(_ tools: [any Tool]) {
        self.tools = Dictionary(tools.map { (type(of: $0).descriptor.name, $0) },
                                uniquingKeysWith: { first, _ in first })
    }

    public func tool(named name: String) -> (any Tool)? { tools[name] }
    public func all() -> [any Tool] { Array(tools.values) }
    public func descriptors() -> [ToolDescriptor] { all().map { type(of: $0).descriptor } }

    /// A new registry with extra tools added (e.g. Cowork's `ask_agent`).
    public func adding(_ extra: [any Tool]) -> ToolRegistry {
        ToolRegistry(all() + extra)
    }

    /// The production read/write/Git/document/browser tool set. Raw `run_shell`
    /// stays implemented for isolated tests/future helper processes but is not
    /// model-exposed because arbitrary commands cannot declare exact touched
    /// paths for WorkspaceLease denied-pattern enforcement.
    public static func standard() -> ToolRegistry {
        ToolRegistry([
            ReadFileTool(), ListFilesTool(), SearchTextTool(), WriteFileTool(),
            ApplyPatchTool(), GitStatusTool(), GitDiffTool(),
            GitStagedDiffTool(), GitInfoTool(), GitRecentCommitsTool(),
            GitDiffBaseTool(), GitBranchTool(), GitCreateBranchTool(),
            GitStageTool(), GitUnstageTool(), GitCommitTool(),
            GitApplyPatchCheckTool(), GitApplyPatchTool(), GitStagePatchTool(),
            GitUnstagePatchTool(), GitRevertPatchTool(), GitWorktreeListTool(),
            GitWorktreeCreateTool(), GitWorktreeRemoveTool(),
            GitRemotesTool(), GitFetchTool(), GitPullFastForwardTool(),
            GitPushTool(), GitSwitchBranchTool(),
            ReadPDFTool(), EditPDFPagesTool(), ReconstructDocumentImageTool(),
            CompileLaTeXTool(), GenerateImageTool(),
            WebFetchTool(), BrowserDiagnosticsTool(), BrowserProfilesTool(), BrowserProfileDeleteTool(), BrowserHistoryTool(),
            BrowserNavigateTool(), BrowserSnapshotTool(), BrowserHandoffTool(), BrowserClickTool(),
            BrowserReloadTool(), BrowserBackTool(), BrowserForwardTool(),
            BrowserTypeTool(), BrowserSubmitTool(), BrowserSelectOptionTool(),
            BrowserPressKeyTool(), BrowserScrollTool(), BrowserWaitTool(), BrowserScreenshotTool(),
            BrowserUploadFileTool(), BrowserDownloadTool(), BrowserDownloadsTool(),
            BrowserSearchTool(),
        ])
    }
}

// MARK: - Small JSON-Schema helpers

enum Schema {
    static let string = JSONValue.object(["type": .string("string")])
    static let nonEmptyString = boundedString(minLength: 1)
    static let integer = JSONValue.object(["type": .string("integer")])
    static let boolean = JSONValue.object(["type": .string("boolean")])

    static func boundedString(minLength: Int? = nil, maxLength: Int? = nil) -> JSONValue {
        var schema: [String: JSONValue] = ["type": .string("string")]
        if let minLength { schema["minLength"] = .number(Double(minLength)) }
        if let maxLength { schema["maxLength"] = .number(Double(maxLength)) }
        return .object(schema)
    }

    static func boundedInteger(minimum: Int? = nil, maximum: Int? = nil) -> JSONValue {
        var schema: [String: JSONValue] = ["type": .string("integer")]
        if let minimum { schema["minimum"] = .number(Double(minimum)) }
        if let maximum { schema["maximum"] = .number(Double(maximum)) }
        return .object(schema)
    }

    static func object(_ properties: [String: JSONValue], required: [String]) -> JSONValue {
        .object([
            "type": .string("object"),
            "properties": .object(properties),
            "required": .array(required.map { .string($0) }),
            "additionalProperties": .bool(false),
        ])
    }
}
